/**
 * Created by linfengluo@gmail.com on 2019/1/7.
 */

const CHANGE_SCROLLER_TOP = 'CHANGE_SCROLLER_TOP'
const CHANGE_PAGE_CONFIG = 'CHANGE_PAGE_CONFIG'
const UPDATE_MODAL_CONFIG = 'UPDATE_MODAL_CONFIG'
const CHANGE_SEARCH_STATE = 'CHANGE_SEARCH_STATE'

export {
  CHANGE_SCROLLER_TOP,
  CHANGE_PAGE_CONFIG,
  CHANGE_SEARCH_STATE,
  UPDATE_MODAL_CONFIG
}
